
/* MFR PATCH: Quote Designer visibility + nav fix */
(function(){
  const EXTRA_NAV = [
    {id:'measurements', label:'Measurements', icon:'📐', top_section:'est', group_label:'Build', display_order:15, description:'Roof measurements, PDF/XML upload, and measurement-driven estimate values', visible:true},
    {id:'quote-designer', label:'Quote Designer', icon:'🎨', top_section:'est', group_label:'Build', display_order:16, description:'Custom quote templates, Canva uploads, and proposal canvas', visible:true}
  ];
  function byId(id){return document.getElementById(id);} 
  function registerQuoteDesignerNav(){
    try{ EXTRA_NAV.forEach(item=>{ PAGE_SECTION[item.id]='est'; }); }catch(_){}
    try{ const arr = window.MFR_NAV_DEFAULTS || (typeof MFR_NAV_DEFAULTS!=='undefined'?MFR_NAV_DEFAULTS:null); if(Array.isArray(arr)){ EXTRA_NAV.forEach(item=>{ if(!arr.some(n=>n.id===item.id)) arr.push(Object.assign({},item)); }); } }catch(_){}
    try{ const arr = window.MFR_NAV_ITEMS || (typeof MFR_NAV_ITEMS!=='undefined'?MFR_NAV_ITEMS:null); if(Array.isArray(arr)){ EXTRA_NAV.forEach(item=>{ if(!arr.some(n=>n.id===item.id)) arr.push(Object.assign({},item)); }); arr.sort((a,b)=>(a.top_section||'ops').localeCompare(b.top_section||'ops') || (a.group_label||'').localeCompare(b.group_label||'') || ((a.display_order||999)-(b.display_order||999))); } }catch(_){}
    try{ if(typeof SECTIONS!=='undefined' && SECTIONS.est && Array.isArray(SECTIONS.est.nav)){ if(!SECTIONS.est.nav.some(n=>n.id==='measurements')) SECTIONS.est.nav.splice(1,0,{id:'measurements',ic:'📐',label:'Measurements'}); if(!SECTIONS.est.nav.some(n=>n.id==='quote-designer')) SECTIONS.est.nav.splice(2,0,{id:'quote-designer',ic:'🎨',label:'Quote Designer'}); } }catch(_){}
  }
  const navCardCss = '<style id="mfr-quote-visible-fix-css">.mfr-quote-tools-card-v2{background:#fff;border:1px solid var(--border,#e2e8f0);border-radius:24px;box-shadow:0 14px 34px rgba(15,23,42,.08);overflow:hidden;margin:0 0 18px}.mfr-quote-tools-card-v2 .mfr-qt-hero{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:22px;background:linear-gradient(135deg,#fff,#eff6ff)}.mfr-qt-kicker{letter-spacing:.16em;text-transform:uppercase;color:#2563eb;font-size:11px;font-weight:950;margin-bottom:6px}.mfr-qt-title{font-size:22px;font-weight:950;color:#0f172a}.mfr-qt-sub{color:#64748b;font-size:13px;font-weight:650;line-height:1.5;max-width:780px;margin-top:4px}.mfr-qt-actions{display:flex;gap:10px;flex-wrap:wrap}.mfr-qt-body{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px}.mfr-qt-tile{display:flex;gap:13px;border:1px solid #e2e8f0;background:#fff;border-radius:18px;padding:16px}.mfr-qt-ic{width:48px;height:48px;border-radius:16px;background:#eff6ff;display:grid;place-items:center;font-size:22px;flex:0 0 auto}.mfr-qt-tile h3{margin:0 0 4px;font-size:16px;color:#0f172a}.mfr-qt-tile p{margin:0 0 12px;color:#64748b;font-size:13px;line-height:1.45}.mfr-qt-mini{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.mfr-qt-chip{border:1px solid #bfdbfe;background:#eff6ff;color:#1d4ed8;border-radius:999px;padding:6px 10px;font-size:11px;font-weight:900}@media(max-width:760px){.mfr-quote-tools-card-v2 .mfr-qt-hero{display:block;padding:18px}.mfr-qt-actions{display:grid;grid-template-columns:1fr;margin-top:14px}.mfr-qt-body{grid-template-columns:1fr;padding:12px}.mfr-qt-tile{display:block}.mfr-qt-ic{margin-bottom:10px}.mfr-qt-actions .btn,.mfr-qt-tile .btn{width:100%}}</style>';
  function ensureCss(){ if(!byId('mfr-quote-visible-fix-css')) document.head.insertAdjacentHTML('beforeend',navCardCss); }
  function toolCard(){return '<div class="mfr-quote-tools-card-v2" id="mfr-quote-tools-card-v2"><div class="mfr-qt-hero"><div><div class="mfr-qt-kicker">Measurements + proposal design</div><div class="mfr-qt-title">Quote Designer & Measurement Center</div><div class="mfr-qt-sub">Bring roof measurements into the estimator, upload measurement reports, attach Canva designs, and build cleaner customer-ready quote proposals.</div><div class="mfr-qt-mini"><span class="mfr-qt-chip">Roof measurements</span><span class="mfr-qt-chip">Canva upload</span><span class="mfr-qt-chip">Quote canvas</span><span class="mfr-qt-chip">PDF proposal</span></div></div><div class="mfr-qt-actions"><button class="btn btn-primary" onclick="mfrOpenMeasurements && mfrOpenMeasurements()">📐 Measurements</button><button class="btn btn-success" onclick="mfrOpenQuoteDesigner && mfrOpenQuoteDesigner()">🎨 Quote Designer</button></div></div><div class="mfr-qt-body"><div class="mfr-qt-tile"><div class="mfr-qt-ic">📐</div><div><h3>Measurement-driven estimating</h3><p>Track roof squares, waste, ridge, eaves, valleys, starter, drip edge, pitch, ventilation, and measurement files.</p><button class="btn btn-outline" onclick="mfrOpenMeasurements && mfrOpenMeasurements()">Open Measurements</button></div></div><div class="mfr-qt-tile"><div class="mfr-qt-ic">🎨</div><div><h3>Custom quote design</h3><p>Choose a quote layout, upload a Canva PNG/JPG/WebP to populate the design canvas, or attach a Canva PDF to the quote.</p><button class="btn btn-outline" onclick="mfrOpenQuoteDesigner && mfrOpenQuoteDesigner()">Open Designer</button></div></div></div></div>';}
  function injectQuoteTools(){ try{ ensureCss(); registerQuoteDesignerNav(); const content=byId('content'); if(!content || byId('mfr-quote-tools-card-v2')) return; const text=(content.textContent||'').toLowerCase(); const looksLikeEstimate=text.includes('build an mfr quote')||text.includes('customer & project')||text.includes('quote summary')||text.includes('estimate builder'); if(!looksLikeEstimate) return; const ref=content.querySelector('.mfr-est-hero')||content.querySelector('.page-hd')||content.querySelector('.card')||content.firstElementChild; if(ref && ref.parentElement) ref.insertAdjacentHTML('afterend', toolCard()); else content.insertAdjacentHTML('afterbegin', toolCard()); }catch(e){console.warn('Quote tools inject skipped',e);} }
  window.mfrInjectQuoteToolsVisibleFix = injectQuoteTools;
  function renderMeasurementsPage(c){ c=c||byId('content'); if(!c) return; c.innerHTML='<div class="page-wrap"><div class="page-hd"><div><div class="page-title">Measurements</div><div class="page-sub">Roof measurements, report uploads, and values that can be applied directly into the estimate builder.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" onclick="mfrOpenMeasurements && mfrOpenMeasurements()">Open Measurement Center</button><button class="btn btn-outline" onclick="go(\'estimates\')">Back to Estimate Builder</button></div></div>'+toolCard()+'</div>'; }
  function renderQuoteDesignerPage(c){ c=c||byId('content'); if(!c) return; c.innerHTML='<div class="page-wrap"><div class="page-hd"><div><div class="page-title">Quote Designer</div><div class="page-sub">Create proposal templates, upload Canva designs, and populate a customer quote canvas with measurement and estimate data.</div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" onclick="mfrOpenQuoteDesigner && mfrOpenQuoteDesigner()">Open Designer</button><button class="btn btn-outline" onclick="go(\'estimates\')">Back to Estimate Builder</button></div></div>'+toolCard()+'</div>'; }
  window.pageMeasurements = async function(c){ registerQuoteDesignerNav(); renderMeasurementsPage(c); };
  const existingQuotePage=window.pageQuoteDesigner;
  window.pageQuoteDesigner = async function(c){ registerQuoteDesignerNav(); if(typeof existingQuotePage==='function'){ try{return existingQuotePage(c);}catch(_){} } renderQuoteDesignerPage(c); };
  function wrapGo(){ registerQuoteDesignerNav(); const oldGo=window.go || (typeof go==='function'?go:null); if(typeof oldGo==='function' && !oldGo.__mfrQuoteVisibleFix){ const fixedGo=function(id){ if(String(id)==='measurements'){ try{_page='measurements';_section='est';_lastPageBySection.est='measurements'; if(typeof syncSectionButtons==='function') syncSectionButtons(); if(typeof buildSB==='function') buildSB();}catch(_){} return renderMeasurementsPage(byId('content')); } if(String(id)==='quote-designer'){ try{_page='quote-designer';_section='est';_lastPageBySection.est='quote-designer'; if(typeof syncSectionButtons==='function') syncSectionButtons(); if(typeof buildSB==='function') buildSB();}catch(_){} return renderQuoteDesignerPage(byId('content')); } const out=oldGo.apply(this,arguments); if(String(id)==='estimates'){ setTimeout(injectQuoteTools,120); setTimeout(injectQuoteTools,500); setTimeout(injectQuoteTools,1100); } return out; }; fixedGo.__mfrQuoteVisibleFix=true; window.go=fixedGo; try{go=fixedGo;}catch(_){} } }
  function boot(){ ensureCss(); wrapGo(); registerQuoteDesignerNav(); setTimeout(function(){try{if(typeof buildSB==='function') buildSB();}catch(_){} injectQuoteTools();},200); setTimeout(injectQuoteTools,800); setTimeout(injectQuoteTools,1600); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot); else boot();
})();
